<a href="https://colab.research.google.com/github/AbhAy120204/movie-classification/blob/master/movie_multi_genre_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

path = kagglehub.dataset_download("rajugc/imdb-movies-dataset-based-on-genre")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/imdb-movies-dataset-based-on-genre

In [2]:
import pandas as pd
import re

In [3]:
genre1 = pd.read_csv(f'{path}/action.csv')
genre2 = pd.read_csv(f'{path}/crime.csv')
genre3 = pd.read_csv(f'{path}/adventure.csv')
genre4 = pd.read_csv(f'{path}/thriller.csv')
genre5 = pd.read_csv(f'{path}/family.csv')
genre6 = pd.read_csv(f'{path}/mystery.csv')
genre7 = pd.read_csv(f'{path}/scifi.csv')
genre8 = pd.read_csv(f'{path}/history.csv')
genre9 = pd.read_csv(f'{path}/sports.csv')
genre10 = pd.read_csv(f'{path}/animation.csv')
genre11 = pd.read_csv(f'{path}/war.csv')
genre12 = pd.read_csv(f'{path}/biography.csv')
genre13 = pd.read_csv(f'{path}/horror.csv')
genre14 = pd.read_csv(f'{path}/fantasy.csv')
genre15 = pd.read_csv(f'{path}/romance.csv')
genre16 = pd.read_csv(f'{path}/film-noir.csv')

In [4]:
df = pd.concat([genre1, genre2, genre3, genre4,
                genre5, genre6, genre7, genre8,
                genre9, genre10, genre11, genre12,
                genre13, genre14, genre15, genre16])

df = df.reset_index(drop=True)

df

,movie_id,movie_name,year,certificate,runtime,genre,rating,description,director,director_id,star,star_id,votes,gross(in $)
0,tt9114286,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,The people of Wakanda fight to protect their h...,Ryan Coogler,/name/nm3363032/,"Letitia Wright, \nLupita Nyong'o, \nDanai Guri...","/name/nm4004793/,/name/nm2143282/,/name/nm1775...",204835.0,NaN
1,tt1630029,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,Jake Sully lives with his newfound family form...,James Cameron,/name/nm0000116/,"Sam Worthington, \nZoe Saldana, \nSigourney We...","/name/nm0941777/,/name/nm0757855/,/name/nm0000...",295119.0,NaN
2,tt5884796,Plane,2023,R,107 min,"Action, Thriller",6.5,A pilot finds himself caught in a war zone aft...,Jean-François Richet,/name/nm0724938/,"Gerard Butler, \nMike Colter, \nTony Goldwyn, ...","/name/nm0124930/,/name/nm1591496/,/name/nm0001...",26220.0,NaN
3,tt6710474,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,A middle-aged Chinese immigrant is swept up in...,"Dan Kwan, \nDaniel Scheinert",/name/nm3453283/,"Michelle Yeoh, \nStephanie Hsu, \nJamie Lee Cu...","/name/nm3215397/,/name/nm0000706/,/name/nm3513...",327858.0,NaN
4,tt5433140,Fast X,2023,NaN,NaN,"Action, Crime, Mystery",NaN,Dom Toretto and his family are targeted by the...,Louis Leterrier,/name/nm0504642/,"Vin Diesel, \nJordana Brewster, \nTyrese Gibso...","/name/nm0004874/,/name/nm0108287/,/name/nm0879...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368295,tt0032257,Black Diamonds,1940,NaN,60 min,"Crime, Drama, Film-Noir",5.5,A reporter on a visit to his hometown hears of...,Christy Cabanne,/name/nm0127511/,"Richard Arlen, \nAndy Devine, \nKathryn Adams,...","/name/nm0035159/,/name/nm0222596/,/name/nm0011...",33.0,NaN
368296,tt0027668,The Gentleman from Louisiana,1936,NaN,67 min,"Crime, Drama, Film-Noir",4.5,"In Victorian-era USA, a horse-jockey becomes a...",Irving Pichel,/name/nm0681635/,"Eddie Quillan, \nCharles 'Chic' Sale, \nCharlo...","/name/nm0703600/,/name/nm0757925/,/name/nm0377...",21.0,NaN
368297,tt0047929,El cerco,1955,NaN,77 min,"Crime, Film-Noir",6.2,A group of robbers assault a factory in the po...,Miguel Iglesias,/name/nm0407071/,"José Guardiola, \nIsabel de Castro, \nÁngel Jo...","/name/nm0345348/,/name/nm0207894/,/name/nm0430...",46.0,NaN
368298,tt0033161,Three Silent Men,1940,NaN,72 min,"Crime, Drama, Film-Noir",5.0,Foreign scientist is selling a secret weapon t...,Thomas Bentley,/name/nm0072872/,"Sebastian Shaw, \nDerrick De Marney, \nPatrici...","/name/nm0789970/,/name/nm0210116/,/name/nm0733...",79.0,NaN
368299,tt0042392,Destination Big House,1950,NaN,60 min,"Crime, Drama, Film-Noir",6.3,School teacher Janet Brooks innocently involve...,George Blair,/name/nm0086251/,"Dorothy Patrick, \nRobert Rockwell, \nJimmy Ly...","/name/nm0665842/,/name/nm0734352/,/name/nm0527...",40.0,NaN

In [5]:
print(f'Duplicates: {df.duplicated().sum()}')

Duplicates: 111199

In [6]:
print("Duplicate movie_id:", df['movie_id'].duplicated().sum())

print("Duplicate movie_name:", df['movie_name'].duplicated().sum())

Duplicate movie_id: 125103
Duplicate movie_name: 154442

In [7]:
df['genre'] = df['genre'].apply(lambda x: [g.strip() for g in x.split(',')] if isinstance(x, str) else [])

df = df.groupby('movie_id').agg({
    'movie_name': 'first',
    'year': 'first',
    'certificate': 'first',
    'runtime': 'first',
    'genre': lambda x: sorted(set(g for sublist in x for g in sublist)),  # merge and deduplicate
    'rating': 'mean',
    'description': 'first',
    'director': 'first',
    'director_id': 'first',
    'star': 'first',
    'star_id': 'first',
    'votes': 'mean',
    'gross(in $)': 'mean'
}).reset_index()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243197 entries, 0 to 243196
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   movie_id     243197 non-null  object
 1   movie_name   243195 non-null  object
 2   year         204302 non-null  object
 3   certificate  55336 non-null   object
 4   runtime      159730 non-null  object
 5   genre        243197 non-null  object
 6   rating       138704 non-null  float64
 7   description  243197 non-null  object
 8   director     222359 non-null  object
 9   director_id  222359 non-null  object
 10  star         198862 non-null  object
 11  star_id      204118 non-null  object
 12  votes        138706 non-null  float64
 13  gross(in $)  12019 non-null   float64
dtypes: float64(3), object(11)
memory usage: 26.0+ MB

In [9]:
def clean_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [10]:
df['description'] = df['description'].apply(clean_text)

In [11]:
all_genres = [genre for genres in df['genre'] for genre in genres]
all_genres[:3]

['Romance', 'Action', 'Adventure']

In [12]:
unique_labels = sorted(set(genre for genres in df['genre'] for genre in genres))
print(len(unique_labels))
print(unique_labels)

27
['Action', 'Adult', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Drama', 'Family', 'Fantasy', 'Film-Noir', 'Game-Show', 'History', 'Horror', 'Music', 'Musical', 'Mystery', 'News', 'Reality-TV', 'Romance', 'Sci-Fi', 'Short', 'Sport', 'Talk-Show', 'Thriller', 'War', 'Western']

In [13]:
id2label = {idx:label for idx, label in enumerate(unique_labels)}
label2id = {label:idx for idx, label in enumerate(unique_labels)}

In [14]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

MODEL = 'distilbert-base-uncased'

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL,
    problem_type = "multi_label_classification",
    num_labels=len(unique_labels),
    id2label=id2label,
    label2id=label2id
    )

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [15]:
import numpy as np
import torch

In [16]:
tokenizer = AutoTokenizer.from_pretrained(MODEL)

In [17]:
def preprocess_data(examples,text_col):
  one_hot_encoded_matrix = []
  text = examples[text_col]
  genres = examples["genre"]
  for genre in genres:
    g = genre
    one_hot_encoded_row = [1 if label in g else 0 for label in unique_labels]
    one_hot_encoded_matrix.append(one_hot_encoded_row)

  one_hot_encoded_matrix = [torch.tensor(o, dtype = torch.float32) for o in one_hot_encoded_matrix]

  encoding = tokenizer(text, truncation=True, max_length=256)

  encoding["labels"] = one_hot_encoded_matrix

  return encoding

In [18]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (2.14.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.15)
Requirement already satisfied: fsspec>=2021.11.1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.11.1->datasets) (2025.3.2)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.31.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0.0,>=0.14.0->datasets) (3.18.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0.0,>=0.14.0->datasets) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [19]:
from sklearn.preprocessing import MultiLabelBinarizer

# Multi-label binarization
mlb = MultiLabelBinarizer()
genre_encoded = pd.DataFrame(mlb.fit_transform(df['genre']), columns=mlb.classes_)

# Combine with the original DataFrame (drop old genre if needed)
df_encoded = pd.concat([df.drop(columns=['genre']), genre_encoded], axis=1)

In [20]:
!pip install iterative-stratification

Requirement already satisfied: iterative-stratification in /usr/local/lib/python3.11/dist-packages (0.1.9)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from iterative-stratification) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from iterative-stratification) (1.15.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from iterative-stratification) (1.6.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->iterative-stratification) (1.5.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->iterative-stratification) (3.6.0)

In [21]:
from iterstrat.ml_stratifiers import MultilabelStratifiedKFold

# X: input features, y: multi-label genre matrix
X = df_encoded[['description']]
y = genre_encoded

# Stratified split
mskf = MultilabelStratifiedKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, test_idx = next(mskf.split(X, y))

# Create train/test DataFrames
train_df = df.iloc[train_idx].reset_index(drop=True)
test_df = df.iloc[test_idx].reset_index(drop=True)

In [22]:
from datasets import Dataset, DatasetDict

# Optional: Keep only relevant columns
train_dataset = Dataset.from_pandas(train_df[['genre', 'description']])
test_dataset = Dataset.from_pandas(test_df[['genre', 'description']])

# Create a DatasetDict for easy model usage
movie_dataset = DatasetDict({
    'train': train_dataset,
    'test': test_dataset
})

In [23]:
movie_dataset

DatasetDict({
    train: Dataset({
        features: ['genre', 'description'],
        num_rows: 194301
    })
    test: Dataset({
        features: ['genre', 'description'],
        num_rows: 48896
    })
})

In [24]:
description_encoded_dataset = movie_dataset.map(
    lambda x: preprocess_data(x, 'description'),
    batched=True,
    batch_size=128,
    remove_columns=['genre', 'description']
)

Map:   0%|          | 0/194301 [00:00<?, ? examples/s]

Map:   0%|          | 0/48896 [00:00<?, ? examples/s]

!labels are mostly 0.0 could be an error

In [25]:
description_encoded_dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 194301
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 48896
    })
})

In [26]:
description_encoded_dataset['train'][0]

{'input_ids': [101, 1996, 7357, 1997, 1037, 2931, 6398, 1999, 1996, 1055, 102],
 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 'labels': [0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0]}

In [27]:
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score
from transformers import EvalPrediction
import torch
import numpy as np
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score, jaccard_score

In [28]:
def multi_label_metrics(predictions, labels, threshold=0.5):

    sigmoid = torch.nn.Sigmoid()

    probs = sigmoid(torch.Tensor(predictions))

    y_pred = np.zeros(probs.shape)
    y_pred[np.where(probs >= threshold)] = 1

    y_true = labels

    f1_micro_average = f1_score(y_true=y_true, y_pred=y_pred, average='micro')
    roc_auc = roc_auc_score(y_true, y_pred, average = 'micro')
    accuracy = accuracy_score(y_true, y_pred)
    jaccard = jaccard_score(y_true, y_pred, average='micro')

    metrics = {'f1': f1_micro_average,
              'roc_auc': roc_auc,
              'accuracy': accuracy,
              'jaccard': jaccard}

    return metrics

def compute_metrics(p: EvalPrediction):

    preds = p.predictions[0] if isinstance(p.predictions, tuple) else p.predictions

    result = multi_label_metrics(predictions=preds, labels=p.label_ids)

    return result

In [29]:
from transformers import TrainingArguments, Trainer, DataCollatorWithPadding
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [33]:
!wandb login --relogin

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin

In [34]:
args = TrainingArguments(
    f"genre-prediction",
    eval_strategy = "epoch",
    save_strategy = "epoch",
    per_device_train_batch_size=16,
    gradient_accumulation_steps=4,
    per_device_eval_batch_size=64,
    num_train_epochs=10,
    logging_steps=10,
    load_best_model_at_end=True,
    metric_for_best_model='jaccard',
)

trainer = Trainer(
    model,
    args,
    train_dataset=description_encoded_dataset["train"],
    eval_dataset=description_encoded_dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

trainer.evaluate()

<ipython-input-34-ed7d4f82eae4>:14: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

{'eval_loss': 0.7024438381195068,
 'eval_model_preparation_time': 0.0015,
 'eval_f1': 0.09159743236495552,
 'eval_roc_auc': 0.41344776073979495,
 'eval_accuracy': 0.0,
 'eval_jaccard': 0.04799691318717207,
 'eval_runtime': 70.9849,
 'eval_samples_per_second': 688.823,
 'eval_steps_per_second': 10.763}

In [35]:
trainer.train()

TrainOutput(global_step=30360, training_loss=0.11592109968618285, metrics={'train_runtime': 9143.4784, 'train_samples_per_second': 212.502, 'train_steps_per_second': 3.32, 'total_flos': 2.4072658171098736e+16, 'train_loss': 0.11592109968618285, 'epoch': 10.0})

In [36]:
trainer.save_model()

In [37]:
from transformers import pipeline, AutoModelForSequenceClassification, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(MODEL)

trained_model = AutoModelForSequenceClassification.from_pretrained(
    f"genre-prediction",
    problem_type = "multi_label_classification",
).eval()

classifier = pipeline('text-classification', model=trained_model, tokenizer=tokenizer, return_all_scores=True)

Device set to use cuda:0
/usr/local/lib/python3.11/dist-packages/transformers/pipelines/text_classification.py:106: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

In [38]:
import random
random_movies = df.sample(3)
texts = list(random_movies['description'])
labels = list(random_movies['genre'])

In [39]:
prediction = classifier(texts)
THRESHOLD = 0.5

prediction = [[label for label in p if label['score'] > THRESHOLD] for p in prediction]

for _text, scores, label in zip(texts, prediction, labels):
  print(_text)
  print('---------------------')
  for _score in sorted(scores, key=lambda x: x['score'], reverse=True):
    print(f'{_score["label"]}: {_score["score"]*100:.2f}%')

  print('actual labels: ', label)
  print('---------------------')

dana a young woman of loose morals dies at the hands of a mentally unstable young man pavel in a fit of jealousy he could not restrain himself and killed the girl with a blow to the see full summary
---------------------
Thriller: 73.85%
actual labels:  ['Crime']
---------------------
abby quinn is eagerly awaiting childbirth but is haunted by dreams where she suffers a miscarriage when she decides to rent a room to a mysterious stranger she realizes a chain of events that will unleash the end of humanity
---------------------
Sci-Fi: 57.17%
Horror: 57.15%
actual labels:  ['Drama', 'Fantasy', 'Horror']
---------------------
george nader heinz weiss heidy bohlen an fbi agent is killed by the mob after making off with five million in gold bars in a robbery gone bad agent jerry cotton is called in to see full summary
---------------------
Crime: 67.38%
Thriller: 65.48%
actual labels:  ['Crime', 'Thriller']
---------------------